### ISSUE TITLE
add url method to view errors and notifications in the browser

### ISSUE THREAD

**Issue by benatkin** [stve/airbrake-api#13]
I'm writing a notifier and one feature I want is a link people can click to view an error or notification. I think once this would be a nice addition to the `Airbrake::Notification` and `Airbrake::Error` classes.

Also there appears to be some duplication between the `Airbrake::Notification` and `Airbrake::Error` classes that could be refactored, and this, if implemented, will add some more duplication.

**Comment by stve** [comment]
There is quite a bit of duplication in there.  I've actually been thinking that the whole interface is overly complicated as it is currently written and have been thinking about moving towards a different interface altogether:

``` ruby
AirbrakeAPI.projects
AirbrakeAPI.error('12345')
AirbrakeAPI.errors
```

This was one of the first API wrappers I built and at the time I was very familiar with ActiveRecord style querying so I emulated that.  Several years later, I'm not as big of a fan of it.

I'm not sure I follow the url method suggestion, can you elaborate?

**Comment by benatkin** [comment]
I want an url to view the error on the Airbrake website - that is, one for HTML, not XML. It doesn't seem to be in the response.

**Comment by stve** [comment]
I see what you mean.  I'll consider that during the refactor.

**Comment by stve** [comment]
In 4.1.0 you can now do:

``` ruby
    AirbrakeAPI.url_for(:error, error_id)
```

`url_for` supports all API endpoints supported by `AirbrakeAPI::Client`, full usage can be seen in the spec: https://github.com/spagalloco/airbrake-api/blob/master/spec/airbrake_api/client_spec.rb#L179-214

Hopefully that's what you were looking for, sorry it took so long to support it.
