### ISSUE TITLE
README is off; can't get anything to work.

### ISSUE THREAD

**Issue by coreyward** [stve/airbrake-api#19]
Working:
- `require 'airbrake-api'`
- `AirbrakeAPI.configure ...`

Not working: 
- Anything else.

I kinda just gave up after these let me down:

``` ruby
AirbrakeAPI.errors #=> NoMethodError: undefined method `errors' for AirbrakeAPI:Module
client = AirbrakeAPI::Client.new #=> <AirbrakeAPI::Client:xxx ...>
client.errors #=> NoMethodError: undefined method `deep_merge' for #<Hash:xxx>
```

Cloning the source and running `rake` let all the tests pass, so I don't know what is up.

**Comment by stve** [comment]
what version of the gem are you using? Significant changes were made in 4.x. It should be backwards compatible though. the syntax you have above is from >=4, is that what you are using?

**Comment by coreyward** [comment]
Using the latest version (4.1, I think;
I'm on my mobile at the moment).

**Comment by stve** [comment]
Ok, so there were a couple things that were screwed up.  The tests didn't actually cover the `connection` method in the Client class and there was a reference to `Hash#deep_merge` which is in ActiveSupport, but if you are using this outside of Rails, that method didn't exist.  Also, delegation to a client via `AirbrakeAPI.errors` was completely unimplemented.

I just released 4.1.1 which fixes both of these issues.  Hopefully it's all working properly now.  Thanks.

**Comment by coreyward** [comment]
Awesome, I'll check it out. Thanks for the quick iteration!

**Comment by stve** [comment]
any luck with 4.1.1?

**Comment by coreyward** [comment]
I'm not getting the same issues, but I am seeing `AirbrakeAPI::AirbrakeError: You are not authorized to see that page.` in response to

``` ruby
AirbrakeAPI::Client.new(auth_token: '...', account: '...').errors
```

**Comment by stve** [comment]
I am getting that error too, I'm trying to get in touch with the guys at Airbrake to see if something's up.  I'm getting 401's from curl as well.

**Comment by stve** [comment]
Ok, turns out what I was doing wrong was using a project's `api_key` instead of the `auth_token` associated with my airbrake account.  Using the `auth_token`, i'm able to get this to work.  Note that if you are using a plan that uses SSL, you'll need to declare that when instantiating the client:

``` ruby
AirbrakeAPI::Client.new(auth_token: '...', account: '...', secure: true).errors
```

**Comment by coreyward** [comment]
Likewise; I'm not entirely sure I understand why there are two, but using the confusingly-similar "auth_token" does allow me to fetch the errors.

Thanks for the help.
