### ISSUE TITLE
your update function shouldn't be using 'collection_path'

### ISSUE THREAD

**Issue by zacksiri** [stve/airbrake-api#2]
in error.rb

it should be using error_path(error) right? since your updating an individual error entry rather than a collection?

correct me if i am wrong

**Comment by stve** [comment]
Seems you are correct, I'll push a fix soon.

**Comment by stve** [comment]
This has been fixed in ade7a8ea6a4e003bbf97cf072356e5eb08175437, I've pushed version 2.4.0 of the gem with this change.  Thanks.
