### ISSUE TITLE
resolving errors

### ISSUE THREAD

**Issue by styliii** [stve/airbrake-api#20]
Trying to resolve an issue using the below syntax.  Although there's no error msg returned, the airbrake error is not updated.  Any thoughts?

AirbrakeAPI::Error.update(51202331, :group => { :resolved => true})

**Comment by stve** [comment]
Thanks for reporting. This gem went through some fairly large changes in 4.x and looks like I broke this along the way.  Please try version 4.1.2 which should resolve this issue.  Thanks.

**Comment by styliii** [comment]
Thanks, it works now.
