### ISSUE TITLE
Notices are not being fetched

### ISSUE THREAD

**Issue by AhmedBelal** [stve/airbrake-api#27]
I just started encountering this issue a few days ago (using 4.2.1). AirbrakeAPI.notices() always seems to return an empty list.

Here is some output from my Rails console:

1.9.3p194 :033 > AirbrakeAPI.errors.size
 => 30 

1.9.3p194 :034 > AirbrakeAPI.errors.first.id
 => 52258487 

1.9.3p194 :035 > AirbrakeAPI.notices(AirbrakeAPI.errors.first.id)
 => [] 

This happens for any error id. Hitting the API directly (e.g. http://app-name.airbrake.io/groups/52258487/notices.xml) shows me a correct list of notices.

Any idea what's going on?

**Comment by stve** [comment]
I'll have a release out soon to resolve this, see #25 and #26 and my report on [Airbrake's support site](http://help.airbrake.io/discussions/questions/977-api-endpoint-change)

**Comment by stve** [comment]
please update to 4.2.2, thanks!

**Comment by AhmedBelal** [comment]
Thanks!
