### ISSUE TITLE
SSL should be enabled

### ISSUE THREAD

**Issue by grosser** [stve/airbrake-api#3]
/usr/local/rvm/gems/ree-1.8.7-2011.03/gems/hoptoad-api-2.4.0/lib/hoptoad-api/client.rb:23:in `fetch': SSL should be enabled - use Hoptoad.secure = true in configuration (Hoptoad::HoptoadError)

if I cannot use it without ssls (error is raised), then please just enable it for me...

**Comment by stve** [comment]
I think Hoptoad may have gone to SSL across the board making this option unnecessary.  If that's the case, then I agree, this should be the default.

**Comment by grosser** [comment]
what i meant was that instead of raising an error, simply enable the option if ssl is detected as necessary

**Comment by stve** [comment]
Good point, it should probably enable the option, then retry the request.  Thanks for all the issues and pull requests, I'm under a deadline, I'll hopefully free up to merge all these changes in this week.

**Comment by benatkin** [comment]
Is this still an issue? Do both the free and paid configurations work?

**Comment by grosser** [comment]
did not encounter this in a long time...
